// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRUDD89_JnswyTl3901glGnX21C84P_EI',
    appId: '1:405215010879:web:2257481d386453eb60988a',
    messagingSenderId: '405215010879',
    projectId: 'assignmentprojects-4af81',
    authDomain: 'assignmentprojects-4af81.firebaseapp.com',
    storageBucket: 'assignmentprojects-4af81.firebasestorage.app',
    measurementId: 'G-V1KJ5TYT1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnAOadXRZWcW4j0xtuPh-8_oyMKpcXhaw',
    appId: '1:405215010879:android:1a2933a923d58e9160988a',
    messagingSenderId: '405215010879',
    projectId: 'assignmentprojects-4af81',
    storageBucket: 'assignmentprojects-4af81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvuyAcx1PeKvav4QMYZciOKHb_-blHdko',
    appId: '1:405215010879:ios:5121b91fb800f46c60988a',
    messagingSenderId: '405215010879',
    projectId: 'assignmentprojects-4af81',
    storageBucket: 'assignmentprojects-4af81.firebasestorage.app',
    iosBundleId: 'com.example.soilo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvuyAcx1PeKvav4QMYZciOKHb_-blHdko',
    appId: '1:405215010879:ios:5121b91fb800f46c60988a',
    messagingSenderId: '405215010879',
    projectId: 'assignmentprojects-4af81',
    storageBucket: 'assignmentprojects-4af81.firebasestorage.app',
    iosBundleId: 'com.example.soilo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRUDD89_JnswyTl3901glGnX21C84P_EI',
    appId: '1:405215010879:web:0a4b34ee7f1955fa60988a',
    messagingSenderId: '405215010879',
    projectId: 'assignmentprojects-4af81',
    authDomain: 'assignmentprojects-4af81.firebaseapp.com',
    storageBucket: 'assignmentprojects-4af81.firebasestorage.app',
    measurementId: 'G-L4PTKD1CRY',
  );
}
